---
apiVersion: 'apps/v1'
kind: 'Deployment'
metadata:
  name: 'dcu-classifier'
  namespace: 'abuse-api-dev'
  labels:
    app: 'dcu-classifier'
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: 'dcu-classifier'
  template:
    metadata:
      labels:
        app: 'dcu-classifier'
    spec:
      imagePullSecrets:
        -
          name: 'dcu-artifactory-creds'
      containers:
        -
          name: 'dcu-classifier'
          imagePullPolicy: 'Always'
          image: 'docker-dcu-local.artifactory.secureserver.net/dcu-classifier:dev'
          livenessProbe:
            exec:
              command:
                - '/app/health.sh'
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
          - name: BUILD_DATE
            value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
          - name: sysenv
            value: dev
          - name: WORKER_MODE
            value: classify
          - name: BROKER_PASS
            valueFrom:
              secretKeyRef:
                name: amqp-dcu-classifier
                key: password
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-dcu-classifier
                key: password
