apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

namespace: abuse-api-prod
images:
- name: docker-dcu-local.artifactory.secureserver.net/dcu-classifier
  newTag: prod
- name: docker-dcu-local.artifactory.secureserver.net/dcu-scanner
  newTag: prod
replicas:
  - count: 2
    name: dcu-classifier
  - count: 4
    name: dcu-scanner

configMapGenerator:
- literals:
  - sysenv=prod
  - LOG_LEVEL=INFO
  - ABUSE_API_CREATE_URL=http://api.abuse-api-prod.svc.cluster.local:5000/v1/abuse/tickets
  - URSULA_API_URL=https://api.phishfeed.com/ursula/v1
  - ELASTIC_APM_ENVIRONMENT=prod
  name: env-specific-values