---
apiVersion: 'extensions/v1beta1'
kind: 'Deployment'
metadata:
  name: 'classifier-celery-beat'
  namespace: 'abuse-api-prod'
  labels:
    app: 'classifier-celery-beat'
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: 'classifier-celery-beat'
    spec:
      imagePullSecrets:
        -
          name: 'dcu-artifactory-creds'
      containers:
        -
          name: 'classifier-celery-beat'
          imagePullPolicy: 'Always'
          image: 'docker-dcu-local.artifactory.secureserver.net/classifier-celery-beat:REPLACE_WITH_GIT_COMMIT'
          env:
          - name: BUILD_DATE
            value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
          - name: sysenv
            value: dev
          - name: BROKER_PASS
            valueFrom:
              secretKeyRef:
                name: amqp-dcu-classifier
                key: password
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-dcu-classifier
                key: password