---
apiVersion: 'apps/v1'
kind: 'Deployment'
metadata:
  name: 'dcu-scanner'
  namespace: 'abuse-api-ote'
  labels:
    app: 'dcu-scanner'
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: 'dcu-scanner'
  template:
    metadata:
      labels:
        app: 'dcu-scanner'
    spec:
      imagePullSecrets:
        -
          name: 'dcu-artifactory-creds'
      containers:
        -
          name: 'dcu-scanner'
          imagePullPolicy: 'Always'
          image: 'docker-dcu-local.artifactory.secureserver.net/dcu-classifier:ote'
          livenessProbe:
            exec:
              command:
                - '/app/health.sh'
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: BUILD_DATE
              value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
            - name: sysenv
              value: ote
            - name: WORKER_MODE
              value: scan
            - name: ML_API_CERT
              value: /mlapicerts/tls.crt
            - name: ML_API_KEY
              value: /mlapicerts/tls.key
            - name: BROKER_PASS
              valueFrom:
                secretKeyRef:
                  name: amqp-dcu-classifier
                  key: password
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-dcu-classifier
                  key: password
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-classifier
                  key: secret
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-classifier
                  key: key
          volumeMounts:
            - name: tls-files-api
              mountPath: /mlapicerts
              readOnly: true
      volumes:
        - name: tls-files-api
          secret:
            secretName: tls-mlapi-api
