apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

namespace: abuse-api-ote

images:
- name: docker-dcu-local.artifactory.secureserver.net/dcu-classifier
  newTag: ote
- name: docker-dcu-local.artifactory.secureserver.net/dcu-scanner
  newTag: ote

configMapGenerator:
- literals:
  - sysenv=ote
  - LOG_LEVEL=DEBUG
  - ABUSE_API_CREATE_URL=https://abuse.api.int.ote-godaddy.com/v1/abuse/tickets
  - URSULA_API_URL=https://api.phishfeed.com/ursula/v1
  - ELASTIC_APM_ENVIRONMENT=ote
  name: env-specific-values
