apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- ingress.yaml

namespace: abuse-api-ote
images:
- name: docker-dcu-local.artifactory.secureserver.net/dcu-classifier
  newTag: ote

configMapGenerator:
- literals:
  - sysenv=ote
  name: env-specific-values