---
apiVersion: 'apps/v1'
kind: 'Deployment'
metadata:
  name: 'classifier-celery-beat'
  labels:
    app: 'classifier-celery-beat'
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: 'classifier-celery-beat'
  template:
    metadata:
      labels:
        app: 'classifier-celery-beat'
    spec:
      imagePullSecrets:
        -
          name: 'dcu-artifactory-creds'
      containers:
        -
          name: 'classifier-celery-beat'
          image: 'docker-dcu-local.artifactory.secureserver.net/classifier-celery-beat'
          envFrom:
            - configMapRef:
                name: env-specific-values
          env:
          - name: MULTIPLE_BROKERS
            valueFrom:
              secretKeyRef:
                name: amqp-shared-creds
                key: multiple_brokers_grandma
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-phishstory-v2
                key: password