---
apiVersion: 'apps/v1'
kind: 'Deployment'
metadata:
  name: 'dcu-scanner'
  labels:
    app: 'dcu-scanner'
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: 'dcu-scanner'
  template:
    metadata:
      labels:
        app: 'dcu-scanner'
    spec:
      imagePullSecrets:
        -
          name: 'dcu-artifactory-creds'
      containers:
        - name: 'dcu-scanner'
          image: 'docker-dcu-local.artifactory.secureserver.net/dcu-classifier'
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          livenessProbe:
            exec:
              command:
                - '/app/health.sh'
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 10
          envFrom:
            - configMapRef:
                name: env-specific-values
          env:
            - name: WORKER_MODE
              value: scan
            - name: MULTIPLE_BROKERS
              valueFrom:
                secretKeyRef:
                  name: amqp-shared-creds
                  key: multiple_brokers_grandma
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-phishstory-v2
                  key: password
            - name: URSULA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ursula-api-token
                  key: token
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: api-scanapi-token
                  key: token
            - name: URSULA_API_ENABLED
              value: 'True'
            - name: SSO_USER
              valueFrom:
                secretKeyRef:
                  name: abuse-api-user
                  key: username
            - name: SSO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: abuse-api-user
                  key: password
            - name: ELASTIC_APM_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: apm-access
                  key: url
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: apm-access
                  key: secret
