---
apiVersion: 'apps/v1'
kind: 'Deployment'
metadata:
  name: 'dcu-scanner'
  namespace: 'abuse-api-dev'
  labels:
    app: 'dcu-scanner'
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: 'dcu-scanner'
  template:
    metadata:
      labels:
        app: 'dcu-scanner'
    spec:
      imagePullSecrets:
        -
          name: 'dcu-artifactory-creds'
      containers:
        - name: wiremock
          imagePullPolicy: Always
          image: docker-dcu-local.artifactory.secureserver.net/dcu-classifier/wiremock:dev
        - name: 'dcu-scanner'
          imagePullPolicy: 'Always'
          image: 'docker-dcu-local.artifactory.secureserver.net/dcu-classifier:dev'
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          livenessProbe:
            exec:
              command:
                - '/app/health.sh'
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: sysenv
              value: dev
            - name: LOG_LEVEL
              value: DEBUG
            - name: WORKER_MODE
              value: scan
            - name: ML_API_CERT
              value: /mlapicerts/tls.crt
            - name: ML_API_KEY
              value: /mlapicerts/tls.key
            - name: MULTIPLE_BROKERS
              valueFrom:
                secretKeyRef:
                  name: amqp-shared-creds
                  key: multiple_brokers_grandma
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-phishstory-v2
                  key: password
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: api-scanapi-token
                  key: token
            - name: ABUSE_API_CREATE_URL
              value: http://api.abuse-api-dev.svc.cluster.local:5000/v1/abuse/tickets
            - name: URSULA_API_URL
              value: http://localhost:8080/ursula/v1
            - name: URSULA_API_KEY
              value: api-key
            - name: URSULA_API_ENABLED
              value: 'True'
            - name: SSO_USER
              valueFrom:
                secretKeyRef:
                  name: abuse-api-user
                  key: username
            - name: SSO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: abuse-api-user
                  key: password
            - name: ELASTIC_APM_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: apm-access
                  key: url
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: apm-access
                  key: secret
            - name: ELASTIC_APM_ENVIRONMENT
              value: dev
          volumeMounts:
            - name: tls-files-api
              mountPath: /mlapicerts
              readOnly: true
      volumes:
        - name: tls-files-api
          secret:
            secretName: tls-mlapi-api
